/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SliceriaIndexImport } from './routes/sliceria/index'
import { Route as SliceriaMenuImport } from './routes/sliceria/menu'
import { Route as SliceriaContactImport } from './routes/sliceria/contact'
import { Route as SliceriaAboutImport } from './routes/sliceria/about'

// Create/Update Routes

const SliceriaIndexRoute = SliceriaIndexImport.update({
  path: '/sliceria/',
  getParentRoute: () => rootRoute,
} as any)

const SliceriaMenuRoute = SliceriaMenuImport.update({
  path: '/sliceria/menu',
  getParentRoute: () => rootRoute,
} as any)

const SliceriaContactRoute = SliceriaContactImport.update({
  path: '/sliceria/contact',
  getParentRoute: () => rootRoute,
} as any)

const SliceriaAboutRoute = SliceriaAboutImport.update({
  path: '/sliceria/about',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sliceria/about': {
      id: '/sliceria/about'
      path: '/sliceria/about'
      fullPath: '/sliceria/about'
      preLoaderRoute: typeof SliceriaAboutImport
      parentRoute: typeof rootRoute
    }
    '/sliceria/contact': {
      id: '/sliceria/contact'
      path: '/sliceria/contact'
      fullPath: '/sliceria/contact'
      preLoaderRoute: typeof SliceriaContactImport
      parentRoute: typeof rootRoute
    }
    '/sliceria/menu': {
      id: '/sliceria/menu'
      path: '/sliceria/menu'
      fullPath: '/sliceria/menu'
      preLoaderRoute: typeof SliceriaMenuImport
      parentRoute: typeof rootRoute
    }
    '/sliceria/': {
      id: '/sliceria/'
      path: '/sliceria'
      fullPath: '/sliceria'
      preLoaderRoute: typeof SliceriaIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/sliceria/about': typeof SliceriaAboutRoute
  '/sliceria/contact': typeof SliceriaContactRoute
  '/sliceria/menu': typeof SliceriaMenuRoute
  '/sliceria': typeof SliceriaIndexRoute
}

export interface FileRoutesByTo {
  '/sliceria/about': typeof SliceriaAboutRoute
  '/sliceria/contact': typeof SliceriaContactRoute
  '/sliceria/menu': typeof SliceriaMenuRoute
  '/sliceria': typeof SliceriaIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/sliceria/about': typeof SliceriaAboutRoute
  '/sliceria/contact': typeof SliceriaContactRoute
  '/sliceria/menu': typeof SliceriaMenuRoute
  '/sliceria/': typeof SliceriaIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sliceria/about'
    | '/sliceria/contact'
    | '/sliceria/menu'
    | '/sliceria'
  fileRoutesByTo: FileRoutesByTo
  to: '/sliceria/about' | '/sliceria/contact' | '/sliceria/menu' | '/sliceria'
  id:
    | '__root__'
    | '/sliceria/about'
    | '/sliceria/contact'
    | '/sliceria/menu'
    | '/sliceria/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SliceriaAboutRoute: typeof SliceriaAboutRoute
  SliceriaContactRoute: typeof SliceriaContactRoute
  SliceriaMenuRoute: typeof SliceriaMenuRoute
  SliceriaIndexRoute: typeof SliceriaIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SliceriaAboutRoute: SliceriaAboutRoute,
  SliceriaContactRoute: SliceriaContactRoute,
  SliceriaMenuRoute: SliceriaMenuRoute,
  SliceriaIndexRoute: SliceriaIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/sliceria/about",
        "/sliceria/contact",
        "/sliceria/menu",
        "/sliceria/"
      ]
    },
    "/sliceria/about": {
      "filePath": "sliceria/about.tsx"
    },
    "/sliceria/contact": {
      "filePath": "sliceria/contact.tsx"
    },
    "/sliceria/menu": {
      "filePath": "sliceria/menu.tsx"
    },
    "/sliceria/": {
      "filePath": "sliceria/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
